MANIFEST

Doing a `perl Makefile.PL` on a clean dist spit out an error about thawte-ec.pem being missing from the kit.  Looks like this file moved into certs/ at some point, and the MANIFEST never got updated.

Fix path to thawte-ec.cert in MANIFEST

---

MANIFEST
t/00-version.t

This diagnostic should make it easier to figure out what version of
OpenSSL is causing the UTF-8 issues on other platforms (via CPANT)

Print OpenSSL version during tests

---

X509.xs

error was:
X509.xs: In function 'XS_Crypt__OpenSSL__X509_extension':
X509.xs:740:10: error: logical not is only applied to the left hand side of comparison [-Werror=logical-not-parentheses]
if (!c > 0) {
^
cc1: all warnings being treated as errors
Makefile:346: recipe for target 'X509.o' failed

fix compilation with gcc5

---

Changes
README
X509.pm

@dsully 
I found the same error as https://github.com/dsully/perl-crypt-openssl-x509/pull/43 also occurs on relatively new version of clang.
```bash
$ cc --version
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.4.0
```
Can you update the version and register it to CPAN?

Bump version to fix compilation errors

---

X509.pm
X509.xs

and keep it working against openssl 1.0.2j
Signed-off-by: Sebastian Andrzej Siewior <sebastian@breakpoint.cc>

libcrypt-openssl-x509-perl: compile against openssl 1.1.0

---

X509.xs

Since OpenSSL 1.1.0, STACK_OF(OPENSSL_STRING) defines
sk_OPENSSL_STRING_num() and other accessors as a functions, not
macros. Thus the #ifndef sk_OPENSSL_STRING_num incorrectly redefined
them and caused fatal warnings about incompatible types.
This patch redefines the accessors only with OpenSSL older than 1.1.0.
<https://github.com/dsully/perl-crypt-openssl-x509/issues/53>

Fix STACK_OF(OPENSSL_STRING) conflicts with OpenSSL 1.1.0

---

.gitignore
Makefile.PL

Apple is no longer supporting OpenSSL, so developers on the Apple platform have the choices of: MacPorts, Homebrew or own installation. This [blog post](https://langui.sh/2015/07/24/osx-clang-include-lib-search-paths/) explains the head aches this causes.
This patch enables the Homebrew installation. I have lifted some code from [perl-crypt-openssl-pkcs12](https://github.com/dsully/perl-crypt-openssl-pkcs12) into the Makefile.PL, so the implementation should be recognisable.
I might do a patch for the MacPorts support if I can find the time, I am not a MacPorts user myself.

Addressed issue with OpenSSL on OSX 10.11, supporting Homebrew installation

---

X509.pm
X509.xs

Having the ASN1 hex is much more useful than just a raw print, which renders all non-printable characters as periods - for many extensions is completely useless. You can still use Extension->as_string() to get a printable string if you need it.

Extension->value() should return asn1parse(1) style hex dump.

---

X509.xs

This is a fix for https://github.com/dsully/perl-crypt-openssl-x509/issues/53#issuecomment-312391444
X509_get0_signature() was introduced to openssl since 1.0.2. See https://www.openssl.org/docs/man1.1.0/crypto/X509_get0_signature.html

fix X509_get0_signature()

---

X509.pm
X509.xs
t/x509.t

Crypt::OpenSSL::X509 doesn't provide an accessor to the issuer's hash, while the library does. This patch exposes that information as a string and creates an alias to the existing hash() accessor (subject_hash) to make it clear which hash you're getting. Updated docs and created tests.

Expose the Issuer's name hash; provide subject_hash() as an alias to hash()

---

META.yml
inc/Module/AutoInstall.pm
inc/Module/Install.pm
inc/Module/Install/AutoInstall.pm
inc/Module/Install/Base.pm
inc/Module/Install/Can.pm
inc/Module/Install/Compiler.pm
inc/Module/Install/External.pm
inc/Module/Install/Fetch.pm
inc/Module/Install/Include.pm
inc/Module/Install/Makefile.pm
inc/Module/Install/Metadata.pm
inc/Module/Install/Win32.pm
inc/Module/Install/WriteAll.pm

Hi @dsully 
This PR updates Module::Install from 1.16 to 1.18 and add the .author directory to `inc/` so the `META.yml` is generated upon build (`perl Makefile.PL`), this should mean no more problems with meta data not being up to date.

Updated Module::Install integration (inc/)

---

Changes
Makefile.PL

I couldn't get this module to install on a Mac or CentOS 7 server. Tweaking the -I and L paths was needed and then I could get it to install
- fixes install problem
- Operating system and version: MacOS 10.14.6, CentOS 7.6.1810
- Crypt::OpenSSL::X509 version: 1.8.12
- Perl version: 5.28.2
- OpenSSL version 1.1.1d
Please see the issue template for a more information on provided the requested information.

Ensure /usr/local is ahead of /usr in include and lib searches

---

X509.pm

This change moves X509 to the lighter XSLoader which needs to do less to start up. Also avoids a `use vars` by simply doing our.
- [X ] New feature (non-breaking change which adds functionality)
- CentOS 7
- master
- Perl 5.32
- OpenSSL version 1.0.2

Switch to Xsloader

---

Makefile.PL
t/utf8.t

Updated Perl minimum requirement to version 5.8, since we specified 5.005, but used newer syntax (5.8)
Actually addresses an unreported issue of the minimum requirement not being correct.

Bump of Perl minimum version requirement

---

Makefile.PL

I created #81, where I suggested that we can use `brew --prefix openssl` to probe openssl libraries.
But it turns out that `brew --prefix openssl` prints a directory even if openssl formula is not installed. I'm sorry.
```
❯ brew --prefix --help
Usage: brew --prefix [--unbrewed] [--installed] [formula ...]
...
If formula is provided, display the location where formula is or would be
installed.
...
--installed                  Outputs nothing and returns a failing
status code if formula is not installed.
```
This PR adds `--installed` option  to `brew --prefix` command so that `brew --prefix` prints a directory only if openssl formula is actually installed. 
- Operating system and version: macOS / linux
- Crypt::OpenSSL::X509 version: 1.906
- …

use --installed option while executing brew

---

.github/workflows/cygwin.yml
.github/workflows/macos.yml
.github/workflows/msys2-mingw.yml
.github/workflows/windows.yml
.gitignore
inc/Module/AutoInstall.pm
inc/Module/Install.pm
inc/Module/Install/AutoInstall.pm
inc/Module/Install/Base.pm
inc/Module/Install/Can.pm
inc/Module/Install/Compiler.pm
inc/Module/Install/External.pm
inc/Module/Install/Fetch.pm
inc/Module/Install/Include.pm
inc/Module/Install/Makefile.pm
inc/Module/Install/Metadata.pm
inc/Module/Install/Win32.pm
inc/Module/Install/WriteAll.pm

Note, that to avoid issues of requiring the installation of Module::Install it was necessary to add the module to the repo.  (otherwise it required the module to be installed as it runs and slows down the completion)
Workflow to test the module against:
1. Windows (Strawberry perl)
2. Windows (cygwin)
3. Windows (msys2-mingw)
4. MacOS
Fixes/addresses (If applicable) # (issue)
Not really any in particular but I was working on the same for Crypt::OpenSSL::Verify and Crypt::OpenSSL::VerifyX509 so I thought I would pass it on since its the basically the same Makefile.PL and format.
Github Actions for testing.
No changes to the base module.  This give automated testing on push to the repo or a fork.  No testing in particular required
- Operating …

GitHub Actions Workflow to Test against Mac and various Windows build methods 

---

X509.xs
t/x509.t

Alias Crypt::OpenSSL::X509::Extension::to_string to Crypt::OpenSSL::X509::Extension::as_string
Fixes #66
- [x ] My code follows the style guidelines of this project
- Redhat 8
- Crypt::OpenSSL::X509 1.9.10 
- Perl version 5.26
- OpenSSL 1.1.1g

Alias as_string as to_string.

---

maint/Makefile_header.PL

LLVM 12.0.0 looks also needing `-Wno-compound-token-split-by-macro` option which has been introduced by #98 for 12.0.5.
- Operating system and version: GitHub Action virtual environment for macos-latest
- Crypt::OpenSSL::X509 version: 1.9.13
- Perl version: 5.34.1, gccversion='Apple LLVM 12.0.0 (clang-1200.0.32.29)'
- OpenSSL version: 1.1.1n

LLVM 12.0.0 also needs workaround

---

maint/Makefile_header.PL

Please include a summary of the proposed improvement or addressed issue.
This does two things:
1. Only enable -Wall and -Werror if the compiler is gcc 
2. Only enable -Werror of $ENV{AUTHOR_TESTING} is set
Fixes/addresses (If applicable) # (issue)
Fixes #95 
Fixes #45 
- Operating system and version 
solaris
Please see the issue template for a more information on provided the requested information.

Only make warnings errors for AUTHOR_TESTING

---

Makefile.PL
cpanfile
maint/Makefile_header.PL

Implementation of https://github.com/dsully/perl-crypt-openssl-x509/issues/97
Crypt::OpenSSL::Guess has support for all use cases implemented in this Makefile.PL

Rewrite to use Crypt::OpenSSL::Guess

---

Makefile.PL
X509.xs
maint/Makefile_header.PL

@jonasbn This is just a test for discussion/review.  I figured before I (or someone else) started on opensslv3 support it would be good to ensure that the current versioning was correct.  This seems to sort a few issue.
I was able to test on:
OpenSSL 1.0.2u  20 Dec 2019
OpenSSL 1.1.1l  24 Aug 2021
Not sure if you have access to 0.9.8 easily.  It took me half the evening to get a 1.0.2 environment running.
Both seemed to work fine and the Makefile.Pl has a couple of options to allow testing it a littl better.
At this point I at least none of the earlier deprecated functions should mess with version 3.
Tim
Tim

Openssl ver updates

---

Makefile.PL
maint/Makefile_header.PL

- Cleaned up in the LLVM CLI flag handling
- Added ALL warning to llvm section
This is a follow up on PR #98 
Please include a summary of the proposed improvement or addressed issue.
Fixes/addresses (If applicable) # (issue)
- Operating system and version
`Darwin silverrocket 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64`
- Crypt::OpenSSL::X509 version
`master` branch
- Perl version
`This is perl 5, version 34, subversion 0 (v5.34.0) built for darwin-2level`
- OpenSSL version
`OpenSSL 1.1.1n  15 Mar 2022`

Clean up to llvm command line options

---

Makefile.PL
maint/Makefile_header.PL

@jonasbn Thank you for releasing Crypt-OpenSSL-X509-1.914-TRIAL!
I found a tiny problem:
On my macOS 12.3 with homebrew's openssl v3, `make` fails:
```
cc -c  -I/usr/local/opt/openssl@3/include -fno-common -DPERL_DARWIN -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV -Wno-error=implicit-function-declaration -DOPENSSL_API_COMPAT=pi_ver -O2 -g -Wall -Wno-deprecated-declarations -Wno-compound-token-split-by-macro   -DVERSION=\"1.914\" -DXS_VERSION=\"1.914\"  "-I/Users/skaji/env/plenv/versions/relocatable-5.34.1.0/lib/5.34.1/darwin-2level/CORE"   X509.c
In file included from X509.xs:5:
In file included from /usr/local/opt/openssl@3/include/openssl/asn1.h:19:
/usr/local/opt/openssl@3/include/openssl/macros.h:155:4: error: "OPENSSL_API_COMPAT …
```

use double quote for interpolation in Makefile.PL

---

.github/workflows/macos-latest.yml

This change explicitly installs OpenSSL version 1. I can see from broken builds that version 3 is used, even though the documentation mentions version 1.
REF: 
- https://github.com/actions/runner-images#available-images
- https://github.com/actions/runner-images/blob/main/images/macos/macos-12-Readme.md
This will be tested using GitHub Actions

Explicitly installing OpenSSL 1 (1.1)

---

Changes.md
X509.pm
X509.xs
dist.ini

This addressed issue described by @dakkar in issue #112 which break building with Crypt::OpenSSL::Verify
Fixes/addresses (If applicable) #112 
- Operating system and version
macOS 13.5 Ventura
- Crypt::OpenSSL::X509 version
1.9.14 (head)
- Perl version
5.36.1
- OpenSSL version
OpenSSL 1.1.1u
Please see the issue template for a more information on provided the requested information.

Reverted changes as proposed by @dakkar in issue #112

---

Makefile.PL
maint/Makefile_header.PL

Fixes issue on AIX where libz is not linked
Fixes/addresses (If applicable) # (issue)
- Operating system and version
- Crypt::OpenSSL::X509 1.915
- Perl version 5.38
- OpenSSL version OpenSSL 1.0.2u  20 Dec 2019

explicitly link libz on AIX
